// actionTypes.js
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const SAVE_CURRENT_PATH = "SAVE_CURRENT_PATH";
export const UPDATE_CART_ITEM_QUANTITY = "UPDATE_CART_ITEM_QUANTITY";
export const CLEAR_CART_ITEMS = 'CLEAR_CART_ITEMS';
export const ORDER_ITEMS = 'ORDER_ITEMS';
export const CLEAR_ORDER_ITEMS = 'CLEAR_ORDER_ITEMS';
